version: '3.8'

services:
  db:
    image: postgres:${POSTGRES_VERSION:-alpine}
    container_name: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env
    environment:
      - PUID=${PUID:-109}
      - PGID=${PGID:-65534}
    networks:
      - backend

  cache:
    image: redis:${REDIS_VERSION:-6.2-alpine}
    container_name: redis
    restart: always
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: redis-server --save 20 1
    volumes: 
      - cache:/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: ${APP_DOCKERFILE:-Dockerfile.app}
    container_name: ${APP_CONTAINER_NAME:-nextcloud}
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ${NEXTCLOUD_EXTDATA:-/mnt/ad/nextcloud}:/extdata
      - php-fpm:/usr/local/etc
      - type: tmpfs
        target: /tmp
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=cache
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-2048M}
    env_file:
      - db.env
    depends_on:
      - db
      - cache
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
    networks:
      - backend

  cron:
    build:
      context: .
      dockerfile: ${APP_DOCKERFILE:-Dockerfile.app}
    container_name: nextcloud-cron
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ${NEXTCLOUD_EXTDATA:-/mnt/ad/nextcloud}:/extdata
      - php-fpm:/usr/local/etc
      - type: tmpfs
        target: /tmp
    entrypoint: /cron.sh
    environment:
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-2048M}
    depends_on:
      - db
      - cache
    networks:
      - backend

  imaginary:
    image: ${IMAGINARY_IMAGE:-ghcr.io/italypaleale/imaginary:master}
    container_name: imaginary
    restart: always
    ports:
      - '${IMAGINARY_PORT:-9000}:9000'
    command: -enable-url-source
    networks:
      - backend

  nginx-proxy:
    image: nginx:${NGINX_VERSION:-alpine}
    container_name: nginx-proxy
    restart: always
    ports:
      - "${NGINX_PORT:-8443}:443"
      - "80:80"
    volumes:
      - sslcerts:/etc/nginx/ssl:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html:ro
    depends_on:
      - app
    networks:
      - backend

volumes:
  db:
  php-fpm:
  nextcloud:
  sslcerts:
  cache:

networks:
  backend:

