services:
  # Serviço do Banco de Dados (MariaDB)
  db:
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud-net

  # Serviço de Cache (Redis)
  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - nextcloud-net

  # Serviço da Aplicação (Nextcloud)
  app:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-app
    restart: unless-stopped
    depends_on:
      - db
      - redis
    volumes:
      - nextcloud-data:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d:ro # Monta a configuração do Nginx para o contêiner web
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - REDIS_HOST=redis
    networks:
      - nextcloud-net

  # Serviço do Servidor Web (Nginx como Proxy Reverso)
  web:
    image: nginx:alpine
    container_name: nextcloud-web
    restart: unless-stopped
    ports:
      - "8080:80" # Expõe a porta 8080 do Pi para a porta 80 do container
    volumes:
      - nextcloud-data:/var/www/html:ro
      - ./nginx/conf.d/nextcloud.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - nextcloud-net

# Definição das Redes e Volumes
networks:
  nextcloud-net:

volumes:
  db-data:
  nextcloud-data:
